SocialNetwork/SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'homepage'),
    
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
]

SocialNetwork/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'accounts/logout.html'), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),

]

SocialNetwork/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.


class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

SocialNetwork/groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()


# Create your models here.



class Group(models.Model):
    name = models.CharField(unique = True, max_length=50)
    slug = models.SlugField(unique = True,allow_unicode=True)
    description = models.TextField(blank = True, default = '')
    description_html = models.TextField(blank = True, default = '', editable=False)
    members = models.ManyToManyField(User, through='GroupMember')
    
    def __str__(self):
        return self.name
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ['name']






class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships')
    user = models.ForeignKey(User, related_name='user_groups')
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')
    

SocialNetwork/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True)
    
    def __str__(self):
        return self.message
    
        
    def save(self,*args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={'username': self.user.username, 'pk': self.pk})
    
    class Meta:
        ordering = ['_created_at']
        unique_together = ('user','message')

    

SocialNetwork/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm



class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def init(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'
        

SocialNetwork/SocialNetwork/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'




class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

SocialNetwork/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView, TemplateView
# Create your views here.


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

SocialNetwork/groups/views.py
from django.shortcuts import render

# Create your views here.

SocialNetwork/posts/views.py
from django.shortcuts import render

# Create your views here.

SocialNetwork/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}


<div class="container">
<h1>Login</h1>
<form method="POST">
	{% csrf_token %}
    {% bootstrap_form form %}
	<input type="submit" class="btn btn-primary" value="Login">
</form>
</div>


{% endblock content %}

SocialNetwork/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}


<div class="container">
<h1>Sign Up</h1>
<form method="POST">
	{% csrf_token %}
    {% bootstrap_form form %}
	<input type="submit" class="btn btn-primary" value="Sign Up">
</form>
</div>


{% endblock content %}

SocialNetwork/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Base</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


    <link rel="stylesheet" href="{% static 'SocialNetwork/static/css/master.css' %}" >

    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet"> 
</head>
<body>





<div class="container">
<div class="jumbotron">

    <nav class="nav navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Home</a>
          </li>





          {% if user.is_authenticated %}
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Post</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Groups</a>
          </li>
                    
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Create a Group</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          </li>
        
          {% else %}
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>
            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Groups</a>
          </li>
  
          {% endif %}
             
        </ul>




</div>
</div>



















<div class="container">
<div class="jumbotron">

<div class="conntent container">
		{% block content %}
    {% endblock content %}
</div>

</div>
</div>






</body> 
</html>

SocialNetwork/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to my social network's first page</h1>
{% endblock content %}

SocialNetwork/templates/test.html
{% extends "base.html" %}

{% block content %}
    <h1>you are now logged in !</h1>
{% endblock content %}

SocialNetwork/templates/thanks.html
{% extends "base.html" %}

{% block content %}
    <h1>thanks for visiting. you are logged out.</h1>
{% endblock content %}